project:
  type: website
  output-dir: docs

website:
  title: "test_shiny_python"
  navbar:
    left:
      - href: index.qmd
        text: TRIZ-39
      - href: about.qmd
        text: TRIZ-45
      - href: 50.qmd
        text: TRIZ-50        
        
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



